sudo: required
language: node_js

node_js:
  - "11" 

services: 
  - docker

before_install:
  - docker build -t elijahprince73/e-commerce-api -f dev.Dockerfile .

scripts:
  - docker run elijahprince73/e-commerce-api npmm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: "e-commerce-api"
  env: "ECommerceApi-env"
  bucket_name: "elasticbeanstalk-us-west-1-784098998479"
  bucket_path: "e-commerce-api"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY