sudo: required
language: node_js

node_js:
  - "11" 

services: 
  - docker

before_install:
  - docker build -t elijahprince73/e-commerce-api -f dev.Dockerfile .

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdn
  - docker push elijahprince73/e-commerce-api